### ISSUE TITLE
Version after 4.1.2 added a dependency on tslib?

### ISSUE THREAD

**Issue by demurray** [tdeekens/promster#356]
After upgrading from 4.1.2 -> 4.1.9 of @promster/express, my application encountered the following error:

```
internal/modules/cjs/loader.js:796
    throw err;
    ^
Error: Cannot find module 'tslib'
Require stack:
- /usr/src/app/node_modules/@promster/express/dist/modules/middleware/middleware.js
- /usr/src/app/node_modules/@promster/express/dist/modules/middleware/index.js
- /usr/src/app/node_modules/@promster/express/dist/modules/index.js
- SNIP
- SNIP
- /usr/src/app/src/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@promster/express/dist/modules/middleware/middleware.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@promster/express/dist/modules/middleware/index.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/@promster/express/dist/modules/middleware/middleware.js',
    '/usr/src/app/node_modules/@promster/express/dist/modules/middleware/index.js',
    '/usr/src/app/node_modules/@promster/express/dist/modules/index.js',
    SNIP,
    SNIP,
    SNIP
  ]
```

`tslib` is not listed as a dependency in https://github.com/tdeekens/promster/blob/master/packages/express/package.json, but in the compiled code under node_modules/@promster/express/dist/modules/middleware/middleware.js, there is

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const http_1 = require("http");
```

I can work around this by requiring `tslib` in my own application, but shouldn't @promster/express require its own dependencies?

**Comment by tdeekens** [comment]
Thanks for reporting. Interesting, I didn't run into this when updating certain apps to the same version and package. Maybe tslib was floating around somewhere already avoiding the issue. I think it's correct what you're suggesting to require tslib within promster.

Would you mind opening a PR to add it as a dependency to all packages?

**Comment by tdeekens** [comment]
Enjoy :)

```txt
Successfully published:
 - @promster/express@4.1.10
 - @promster/fastify@3.1.9
 - @promster/hapi@4.1.9
 - @promster/marblejs@3.1.10
 - @promster/metrics@4.1.9
 - @promster/server@4.2.11
 - @promster/types@1.0.4
```

**Comment by demurray** [comment]
Thank for jumping on this. Can confirm that this fixes the error for me.
