### ISSUE TITLE
Hapi plugin package.json require path is wrong

### ISSUE THREAD

**Issue by teemuhirsikangas** [tdeekens/promster#6]
```
npm i @promster/hapi --save
npm install
```
added this to my project
`const { createPlugin } = require('@promster/hapi');`

started the app:
-> error:

```
 Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:547:15)
     at Function.Module._load (module.js:474:25)
     at Module.require (module.js:596:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/home/project/node_modules/@promster/hapi/modules/plugin/plugin.js:1:75)

```
comes from this line:
https://github.com/tdeekens/promster/blob/90db74abfd170762e1f060c18d218c84136cac41/packages/hapi/modules/plugin/plugin.js#L1

**Comment by tdeekens** [comment]
Sorry about that. Sadly I was only able to use the express version so far.

That said: I started working on v1.0.0 last night which also gives you:

1. Automatic garbage collection stats
2. Configurable second or millisecond accuracy (just pass `accuracies: ['ms']` in the options)
   - Given you want to keep ms. In Prometheus land second is the "defacto standard" now
   - You can also pass both if you need to migrate

Would you mind trying out installing `@promster/hapi@1.0.0-beta.4`? It's on the `@next` tag currently so see if things work there for you? This weekend I plan to add better tests to everything.

**Comment by tdeekens** [comment]
Alright, I had some time to fixup things in `1.0.0-beta.5`. I use it now in one of our hapi based apps and it for me. Note that it requires hapi@17.

**Comment by tdeekens** [comment]
Lovely. Thanks for your patience.
